env:
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: xterm-256color

window:
  opacity: 0.9999
  padding:
    x: 0
    y: 0
  decorations: full
  startup_mode: Maximized
  dimensions:
    columns: 180
    lines: 50

cursor:
  style:
    shape: Underline
    blinking: Always
    blink_interval: 500

font:
  normal:
    # Needs to be powerline font if using zsh theme with powerline
    family: Liga DejaVuSansM Nerd Font Mono
  size: 18
  offset:
    x: 1
    y: 1

colors:
  primary:
    background: "#262A33"
    foreground: "#f8f8f2"
    bright_foreground: "#ffffff"
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: "#44475a"
      background: "#50fa7b"
    focused_match:
      foreground: "#44475a"
      background: "#ffb86c"
  footer_bar:
    background: "#262A33"
    foreground: "#f8f8f2"
  hints:
    start:
      foreground: "#262A33"
      background: "#f1fa8c"
    end:
      foreground: "#f1fa8c"
      background: "#262A33"
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: "#44475a"
  normal:
    black: "#21222c"
    red: "#ff5555"
    green: "#50fa7b"
    yellow: "#f1fa8c"
    blue: "#bd93f9"
    magenta: "#ff79c6"
    cyan: "#8be9fd"
    white: "#f8f8f2"
  bright:
    black: "#6272a4"
    red: "#ff6e6e"
    green: "#69ff94"
    yellow: "#ffffa5"
    blue: "#d6acff"
    magenta: "#ff92df"
    cyan: "#a4ffff"
    white: "#ffffff"

selection:
  # This string contains all characters that are used as separators for
  # "semantic words" in Alacritty.
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"

  # When true, selected text will be copied to the primary clipboard
  save_to_clipboard: true

# Login shell with arguments
shell:
  program: /bin/zsh
  args:
    - --login

# Startup directory, unset or None for home directory
working_directory: None

